### ISSUE TITLE
2.7.0 broke.

### ISSUE THREAD

**Issue by atian25** [fgnass/node-dev#102]
now it don't support `--harmony`, `--debug-brk`, `--debug`

**Comment by fgnass** [comment]
Bummer. I should have thought of that, thanks for reporting!

@gasi I don't want to list every possible v8 option (as this would tie node-dev to a specific engine version). Instead all unknown args should be passed the node binary (as it used to before). I'm not sure if this is possible with commander, but substack's https://github.com/substack/minimist has pretty decent support for unknown arguments.

**Comment by atian25** [comment]
https://github.com/tj/commander.js/pull/310

**Comment by gasi** [comment]
Sorry for the breakage and great find, @atian25. Would you be interested to submit a PR with the change to support unknown options + tests? I’d be happy to review it.

**Comment by matthewmueller** [comment]
+1, this just broke a ton of our stuff haha.

**Comment by fgnass** [comment]
The new version is now published as 2.7.1.

**Comment by gasi** [comment]
@fgnass I was planning to undo the `commander` change and push 2.7.1, but this is much better — thanks :+1:
