### ISSUE TITLE
What does child.respawn mean?

### ISSUE THREAD

**Issue by jiyinyiyong** [fgnass/node-dev#104]
I remmemberd `node-dev a.js` will always runs until I press Command-C to kill it. But for quite long time it's not. It stops as long as the program exits, and keeps running when there's an event loop or something. So I looked into the code today and found `child.respawn` to be `undefined`.

```js
  function start() {
    var cmd = nodeArgs.concat(wrapper, script, scriptArgs)
    child = fork(cmd[0], cmd.slice(1), {
      cwd: process.cwd(),
      env: process.env
    })
    .on('exit', function(code) {
      console.log(child, child.respawn) // <-- undefined
      if (!child.respawn) process.exit(code)
      child = undefined
    })
```
```js
  function stop() {
    child.respawn = true
    child.kill('SIGTERM')
    child.disconnect()
  }
```
```
➤➤ uname -a
Darwin Air.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 16 23:12:31 PDT 2015; root:xnu-2782.20.48~4/RELEASE_X86_64 x86_64
➤➤ node -v
v0.12.5
```

Any ideas on why it's happing? Or is it designed to behave like that?

**Comment by jiyinyiyong** [comment]
@fgnass ping?

**Comment by fgnass** [comment]
This is by design. The idea is that `node-dev` should behave exactly the same way as `node` does. But we could consider adding a `--respawn` command line option that brings back the old beahivor.

**Comment by fgnass** [comment]
To answer the question in the issue's title: The `respawn` flag is set to distinguish exits that were caused by node-dev from process terminations that where the initiated by the child process itself.
