### ISSUE TITLE
Deprecated version of object-keys in use

### ISSUE THREAD

**Issue by mietennet** [fgnass/node-dev#106]
$ npm install -g node-dev
npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys

$ npm ls -g object-keys
/usr/local/lib
└─┬ node-dev@2.7.1
  └─┬ dynamic-dedupe@0.2.0
    └─┬ xtend@2.0.6
      └── object-keys@0.2.0

**Comment by fgnass** [comment]
See: https://github.com/thlorenz/dynamic-dedupe/issues/2
