### ISSUE TITLE
notifications are not working on node version v5.6.0 v5.5.0 on mac el capitan

### ISSUE THREAD

**Issue by parinck** [fgnass/node-dev#126]

**Comment by Flet** [comment]
Its possible its related to the recent commit that added `--no-notify`...
https://github.com/fgnass/node-dev/commit/e915c813e0a635b62a5864ad32558bc89505070e

I added the `--notify` flag and I get notifications... give that a try?

**Comment by parinck** [comment]
Yup notifications are back. But is there anyway to turn notifications by default ?

**Comment by fgnass** [comment]
Notifications are now on again by default in v3.1.1.
