### ISSUE TITLE
Don't set NODE_ENV

### ISSUE THREAD

**Issue by aseemk** [fgnass/node-dev#133]
Hey @fgnass (and contributors), great ongoing work. We've been using node-dev for several years now and it's been awesome.

We just updated after a long time, and we hit the same issue with node-dev now setting `NODE_ENV` that @gasi did in https://github.com/fgnass/node-dev/issues/62#issuecomment-131992922.

It sounded like you agreed that node-dev should just not set `NODE_ENV` at all, since the caller who's calling `node-dev` can always set any environment variable they want. (Put another way, `NODE_ENV=development` doesn't tell you you're running in node-dev, so it's not serving that purpose. Instead, it's just assuming that code wants to set `NODE_ENV` by default, and to `development`.)

If that's still the case, I wanted to open this issue to capture this request. Would be great to have node-dev no longer set `NODE_ENV`! Thanks for your consideration. =)

**Comment by fgnass** [comment]
You're absolutely right. As we agreed on not setting it at all, I would consider this as bug that should be fixed.

**Comment by whitecolor** [comment]
And I could not set custom NODE_ENV  via command line.

**Comment by brainsandspace** [comment]
any update on this?
