### ISSUE TITLE
Error with dust.js

### ISSUE THREAD

**Issue by leaves4j** [fgnass/node-dev#136]
I use dust.js in my project ,run `node app.js` work well ,but it's error with `node-dev`,
node version v6.2, node-dev version is 3.1.1,error is 

`Cannot read property 'filename' of undefined
at Object.obj.(anonymous function) [as runInContext] (/usr/local/lib/node_modules/node-dev/lib/hook.js:25:55)`

**Comment by fgnass** [comment]
This should be fixed by #135. Patch landed in v3.1.3.
