### ISSUE TITLE
Add default loader for typescript?

### ISSUE THREAD

**Issue by pyros2097** [fgnass/node-dev#182]
How a about adding a  default extension loader for typescript? 
Like this one 'ts-node/register' or adding a command line option to register the service like mocha does? because I need to create the json file just for that one extension

**Comment by whitecolor** [comment]
There is `-r` option. You may use `node-dev -r ts-node/require app`

**Comment by pyros2097** [comment]
Yeah just checked it,
Its this
`node-dev -r ts-node/register app.js`

Maybe this should be in the docs somewhere.
