### ISSUE TITLE
How to get this to work with ES6 babel-node

### ISSUE THREAD

**Issue by tgoldenberg** [fgnass/node-dev#195]
I realize that the README describes a `node-dev.json` file to set extension settings, but it is not clear to me how to get this to work with `babel-node.` Currently I'm running my server.js code with the command `./node_modules/.bin/babel-node server/`. When I run the command with `node-dev`, `node-dev server`, I get the error `Unexpected token import`. My `node-dev.json` file is like so:

```
{
  "extensions": {
    "js": {
      "name": "babel/register"
    }
  }
}
```

Any suggestions would be very welcome!

**Comment by kenberkeley** [comment]
+1

**Comment by shinji19** [comment]
In my environment it worked on the following ...
.babelrc
```
{
  "presets": ["es2015"]
}
```

**Comment by amosyuen** [comment]
@tgoldenberg I'm trying to do the same thing, but even if I require `babel-register` and `babel-polyfill` at the top of my `server.pi` I still run into the `Unexpected token import` error. Did you have any other configuration?

This is what my `.babelrc` looks like:
```
{
  "plugins": [
    "babel-plugin-syntax-dynamic-import",
    "babel-plugin-transform-class-properties",
    "babel-plugin-transform-object-rest-spread"
  ],
  "presets": [
    [
      "env",
      {
        "targets": {
          "node": "current"
        }
      }
    ]
  ]
}
```

**Comment by amosyuen** [comment]
After some playing around, looks like instead of requiring`babel-register` setting this in my `.node-dev.json`  did the trick:
```
{
  "extensions": {
    "js": {
      "name": "babel/register"
    }
  }
}
```

**Comment by kenberkeley** [comment]
In addition to @amosyuen 's `.node-dev.json`, you might need a `.babelrc` in the same directory:

```json
{
  "presets": ["stage-2"]
}
```
