### ISSUE TITLE
node-dev only reacts once a file has been saved

### ISSUE THREAD

**Issue by radical-edo** [fgnass/node-dev#196]
I've been using `node-dev` for quite some time, so this is a bit surprise for me.

I've bumped `Node` to `7.3` and now `node-dev` only restarts once after the initial restart. Meaning I save the file, it restarts. Then when I make a change it will do nothing.

When working with `Node` 6+ there are no issues.

Am I the only one who has this problem?

**Comment by henrahmagix** [comment]
node 7.5.0 and node-dev 3.1.3 works fine for me: restarts for all changes to all required files.
