### ISSUE TITLE
Does it work with native ES6 modules?

### ISSUE THREAD

**Issue by darkbasic** [fgnass/node-dev#201]
Does it work with native ES6 modules?

**Comment by ravshansbox** [comment]
You have to use a transpiler like babel.

**Comment by vilic** [comment]
@darkbasic I made an alternative using a different (and way simpler) mechanism that supports ES6 module. https://github.com/makeflow/nodemand

**Comment by wang1212** [comment]
Today, **ES Module** has received good official support from Node, but I found that it still does not work as expected:

`Node v14.17.4`

According to the [official document](https://nodejs.org/api/packages.html#packages_type):

> `import` statements of `.js` files are treated as ES modules if the nearest parent `package.json` contains `"type": "module"`.

But I found that an error will occur: `Error [ERR_REQUIRE_ESM]: Must use import to load ES Module`. When I change the file suffix to `.mjs`, it works normally.

Of course, I also tried `nodemon` and found that both `.js` and `.mjs` can work normally.

**Comment by lehni** [comment]
I have created a PR to fix this problem: #274

**Comment by lehni** [comment]
@bjornstar this issue is resolved and can be closed now!

**Comment by bjornstar** [comment]
Fixed in [v7.3.0](https://github.com/fgnass/node-dev/releases/tag/v7.3.0)
