### ISSUE TITLE
Piping output causes segmentation fault in Git Bash on Windows using Node.js 8.9.4

### ISSUE THREAD

**Issue by laurence-myers** [fgnass/node-dev#208]
## Steps to reproduce

1. Install and open Git Bash (using the MinTTY console)
1. `mkdir node-dev-issue`
1. `cd node-dev-issue`
1. `npm init`
1. `npm install node-dev`
1. `echo "console.log('Hello world\!')" > index.js`
1. `./node_modules/.bin/node-dev index.js | cat`

## Output
```
Hello world!
./node_modules/.bin/node-dev: line 14: 13568 Segmentation fault      node "$basedir/../node-dev/bin/node-dev" "$@"
```

## Notes

- In the real world, we pipe from node-dev to bunyan
- Piping from node-dev to bunyan works fine when run from Windows Command Prompt
- It used to work in Node 6.9.1 just fine. We recently upgraded to Node 8.9.4, and started getting this issue.

## Environment

- Windows 10
- Node.js 8.9.4
- npm 5.6.0
- Git Bash 2.16.1.4-64-bit
- node-dev 3.1.3

**Comment by laurence-myers** [comment]
nodemon exhibits this same issue, so it's probably just a Git Bash issue.

**Comment by bjornstar** [comment]
Sounds like this is resolved.
