### ISSUE TITLE
Exit on SIGTERM signal

### ISSUE THREAD

**Issue by EmrysMyrddin** [fgnass/node-dev#210]
It seems that `node-dev` doesn't handle the SIGTERM signal.

This is particulary annoying when running it as Entrypoint of a docker image. It makes shuting the docker container really slow (it waits until a fix timeout that `node-dev` gracefully exists before killing it).

**Comment by johntran** [comment]
I would recommend switching to `nodemon`. Seems like this project is not maintained anymore.

**Comment by bjornstar** [comment]
It should be handling SIGTERM currently, please reopen if you're still having issues.
