### ISSUE TITLE
How can we use --experimental-modules with node v10?

### ISSUE THREAD

**Issue by ericfong** [fgnass/node-dev#212]
Pass all unknown args to node?

**Comment by daveisfera** [comment]
We use `esm` so we can use `import` in our client and server code and we'd like to switch to using the built-in ESM support in node 14, but passing `--experimental-specifier-resolution=node` to `node-dev` doesn't work, so it would be nice to be able to do that

**Comment by bjornstar** [comment]
> We use `esm` so we can use `import` in our client and server code and we'd like to switch to using the built-in ESM support in node 14, but passing `--experimental-specifier-resolution=node` to `node-dev` doesn't work, so it would be nice to be able to do that

I've been trying out ESM and got it working with node-dev locally without needing to pass args I can publish that pretty easily. That being said I still want to look into passing node args for experimental loader support.

**Comment by daveisfera** [comment]
Is there a way to have `.js` files resolved as ESM to use the `import` syntax? And how about imports without extension?

Or is using `--experimental-specifier-resolution=node` the best option for that?

**Comment by jonataswalker** [comment]
Looks like we'll have to wait a bit.
