### ISSUE TITLE
Current project status

### ISSUE THREAD

**Issue by DanielRuf** [fgnass/node-dev#215]
Hi, what is the current status of this project? Is it still actively maintained?

**Comment by lonix1** [comment]
@fgnass I assume from your comment that you are currently using something "better"... Would you mind saying what it is, and whether you recommend it?

**Comment by bjornstar** [comment]
@fgnass I would like to help maintain node-dev as I use it on a daily basis. I'm primarily interested in just getting dependencies updated and not changing functionality. If you're up for giving me commit and publishing rights, I'm also bjornstar on npm.

**Comment by fgnass** [comment]
@bjornstar awesome, thanks! You help is much appreciated! I added you as collaborator both here and on npm.

**Comment by bjornstar** [comment]
@fgnass I've tagged v4.0.0 and released on npm. Thanks for letting me help out.

I'm planning on getting the rest of the dependencies up to date in another release. Once that is done I'll take a look at the pending PRs.

@DanielRuf, if there's anything specific you'd like addressed feel free to re-open the issue.
