### ISSUE TITLE
notify option no longer works when set in .node-dev.json

### ISSUE THREAD

**Issue by ianwalter** [fgnass/node-dev#229]
I think there should be a "not undefined" condition here so that it does not get overwritten by the CLI options:
https://github.com/fgnass/node-dev/commit/e17baec4c111e7ee31653104d5bb3c10b344b65e#diff-48207702c14d7936c39cbc1317b1e3a5R30

**Comment by bjornstar** [comment]
Sorry about that, if you look at the `CHANGELOG` you can see there have been a lot of issues with options not behaving as expected and having to be "fixed" multiple times.

I've gone ahead and rewritten the CLI & config to be consistent and hopefully we can avoid more of these issues in the future.
