### ISSUE TITLE
Broken in TypeScript 4.5.3

### ISSUE THREAD

**Issue by hornta** [fgnass/node-dev#287]
TypeScript 4.5.3
Platform: Windows 10
node: 17.9.0
node-dev: 7.4.1

```sh
PS C:\Users\hornta\Desktop\recipes\packages\scraper> node-dev ./src/index.ts
Debugger listening on ws://127.0.0.1:60616/76e837a4-c371-48d0-b358-b7da37bc5b8b
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
(node:71788) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time    
(Use `node --trace-warnings ...` to show where the warning was created)
TypeError [ERR_INVALID_RETURN_PROPERTY_VALUE]: Expected string, array buffer, or typed array to be returned for the "source" from the "load" function but got type object.
    at new NodeError (node:internal/errors:372:5)
    at assertBufferSource (node:internal/modules/esm/translators:82:9)
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:113:3)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:361:14)
    at async link (node:internal/modules/esm/module_job:70:21)
Waiting for the debugger to disconnect...
[ERROR] 23:10:00 TypeError: Expected string, array buffer, or typed array to be returned for the "source" from the "load" 
function but got type object.
```

**Comment by bjornstar** [comment]
I think the problem is that we handle the `ERR_UNKNOWN_FILE_EXTENSION` error when loading `builtin` modules and do not surface that error to the user.

My guess is that you have `"type": "module"` in your `package.json` and this won't work with `ts-node`. I can fix the error handling so it surfaces the error more directly to you.

**Comment by hornta** [comment]
So the combination of `"type": "module"` and `ts-node` isn't supported in node-dev? Because this combination works when running straight from ts-node.

**Comment by bjornstar** [comment]
The default configuration for ts-node is via commonjs (`ts-node/register`)

The problem is that node doesn't support multiple loaders for ESM. Only one loader will actually be loaded.

Maybe someone can make a combined ts-node/esm + node-dev loader or find another solution.

**Comment by maxpain** [comment]
Any updates?
