### ISSUE TITLE
Suppress experimental warnings with Node v18

### ISSUE THREAD

**Issue by tmont** [fgnass/node-dev#293]
```
$ cat test.js
console.log('hello world');

$ node_modules/.bin/node-dev test.js
(node:2550900) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
hello world
```

I saw that file conveniently called `suppress-experimental-warnings.js` but either it doesn't work or it doesn't work with Node v18.

It looks like something internal changed at some point in the way warnings are emitted according to this comment: https://github.com/nodejs/node/issues/30810#issuecomment-1107876903

**Comment by MohamadKh75** [comment]
any updates?

cc @fgnass
