### ISSUE TITLE
Using node-dev in a shared folder in a virtualbox guest

### ISSUE THREAD

**Issue by pepve** [fgnass/node-dev#87]
I've recently started using vagrant (with virtualbox) for my development environment. I've set it up so that my node project directory is shared to the vm. I then run the project in the vm, and edit the files on my own system (the host). The problem is that the virtualbox shared folder doesn't (and won't) support file system events. So for edits that are done on the host system, node-dev doesn't work.

I created [a solution to this problem](https://github.com/pepve/node-dev/commit/aa096c4b70bccdde04c89ce64a6c467b4fbc5798). And I'd like to know if this functionality is something you would consider merging (but maybe in a different implementation).

It works like this: on the host system you run (in the project directory) `node-dev --listen 0.0.0.0:45654`, in the guest vm you run `node-dev --remote 192.168.0.1:45654 server.js` (where 192.168.0.1 is the IP address of you host system in the virtual network).

**Comment by pepve** [comment]
@fgnass In a belated response to your comment [here](https://github.com/pepve/node-dev/commit/aa096c4b70bccdde04c89ce64a6c467b4fbc5798#commitcomment-8226008) I've created [a new approach](https://github.com/pepve/node-dev/commit/3df2713d569d6da42a943538061b2aba6387d132) to the problem. Please let me know what you think. If you're okay with this one I'll release version 1.0.0 of [remote-filewatcher](https://github.com/pepve/remote-filewatcher) (the new dependency that does the bulk of the work) and submit a pull request.

**Comment by fgnass** [comment]
:+1: Awesome! Can you make this a pull request?

**Comment by fgnass** [comment]
I did some work on filewatcher yesterday and think the easiest way to support your use-case would be to pass `{polling: true}` to the filewatcher instance. According to the docs this should work on network filesystems too.

**Comment by davejamesmiller** [comment]
I have the same issue. Is there any way to pass `{polling: true}` to the filewatcher instance? As far as I can tell from [the code](https://github.com/fgnass/node-dev/blob/18192c043f25024c97f59bb2df6bb737f1f525e6/lib/index.js#L25) this is currently not possible? I'd like to be able to pass it in as a config option... Thanks!

**Comment by bjornstar** [comment]
Looks like this was implemented a while ago.
