### ISSUE TITLE
No error stack output (TypeError)

### ISSUE THREAD

**Issue by whitecolor** [fgnass/node-dev#94]
Simple example:

```javascript
var A = function(){}
var a = new A()
// trying to call not existing method on the instance
a.method()
```

node-dev gives just one line (whtout error stack)
```
[ERROR] 06:17:30 TypeError
```

`node` (or for example `nodemon` as alternative) in the same case gives an error:
```
path\to\file\test-node-dev.js:5
a.method()
  ^
TypeError: undefined is not a function
    at Object.<anonymous> (path\to\file\test-node-dev.js:5:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

I'm running windows x64, node 0.12

**Comment by whitecolor** [comment]
Any comment?

**Comment by fgnass** [comment]
Maybe this is Windows-only issue? This is what `node-dev` does to log the error:

```js
process.on('uncaughtException', function(err) {
 console.error(err.stack || err)
})
```

On OS X this yields the following output:

![screen shot 2015-05-16 at 13 41 39](https://cloud.githubusercontent.com/assets/89450/7665992/95e65ca0-fbd1-11e4-91c7-c3e7be8521a0.png)

Maybe `console.error()` which writes to STDOUT gets swallowed in your case? Could you change https://github.com/fgnass/node-dev/blob/master/lib/wrap.js#L43 to `console.log()` and let me knows if this has any impact on the output you see?

**Comment by jsen-** [comment]
The same thing happens to me (win64 too). On the first run, I see the stack trace, but consecutive runs - after automatic restart, the stack trace is missing. I'm not at the computer now, so I'll provide additional info on Sunday evening.

**Comment by fgnass** [comment]
I just published `2.6.2` with the following improvement: https://github.com/fgnass/node-dev/commit/2a81bfa52f07990f133487963e409238a23ef528

My guess is that in some cases the child process gets killed before it can log the message. Let me know if this fixes your issue.

**Comment by jsen-** [comment]
Seems to be working just fine in 2.6.2. Thanks for super quick response, Felix.

**Comment by whitecolor** [comment]
If it appears to be fix I'll close the issue, thanks.
